# Live Scoreboard
GAME_ID = "gameId"
GAME_STATUS = "gameStatus"
GAME_STATUS_TEXT = "gameStatusText"
GAME_ET = "gameEt"
HOME_TEAM = "homeTeam"
AWAY_TEAM = "awayTeam"
TEAM_ID = "teamId"
TEAM_NAME = "teamName"
TEAM_CITY = "teamCity"
SCORE = "score"

# LeagueStandingsV3
TEAM_ID_STANDING = "TeamID"
TEAM_NAME_STANDING = "TeamName"
TEAM_CITY_STANDING = "TeamCity"
WINS_STANDING = "WINS"
LOSSES_STANDING = "LOSSES"
LAST_10_STANDING = "L10"
CONFERENCE_STANDING = "Conference"

# ScoreboardV2, BoxScoreTraditionalV2
GAME_ID_SCHEDULE = "GAME_ID"
GAME_DATE_EST_SCHEDULE = "GAME_DATE_EST"
GAME_STATUS_TEXT_SCHEDULE = "GAME_STATUS_TEXT"
GAME_STATUS_ID_SCHEDULE = "GAME_STATUS_ID"

TEAM_ID_SCHEDULE = "TEAM_ID"
TEAM_NAME_SCHEDULE = "TEAM_NAME"
TEAM_CITY_SCHEDULE = "TEAM_CITY"
PTS_SCHEDULE = "PTS"

HOME_TEAM_ID_SCHEDULE = "HOME_TEAM_ID"
AWAY_TEAM_ID_SCHEDULE = "VISITOR_TEAM_ID"

TEAM_INFO_NICKNAME_SCHEDULE = "NICKNAME"
TEAM_INFO_CITY_SCHEDULE = "CITY"

# Outputs
WINS_OUTPUT = "wins"
LOSSES_OUTPUT = "losses"
LAST_10_OUTPUT = "last_10"
CONFERENCE_OUTPUT = "conference"
